import json, urllib.request, urllib.error, base64, ssl, certifi, os

JIRA_URL = "https://smartship.atlassian.net"
JIRA_EMAIL = "sarah_suda@epam.com"
JIRA_TOKEN = os.environ.get("JIRA_TOKEN", "")
auth = base64.b64encode(f"{JIRA_EMAIL}:{JIRA_TOKEN}".encode()).decode()

def para(t): return {"type":"paragraph","content":[{"type":"text","text":t}]}
def h(t, l=2): return {"type":"heading","attrs":{"level":l},"content":[{"type":"text","text":t}]}
def bullets(items): return {"type":"bulletList","content":[{"type":"listItem","content":[para(i)]} for i in items]}
def link(text, url): return {"type":"inlineCard","attrs":{"url":url}}

def para_with_link(prefix, text, url, suffix=""):
    content = []
    if prefix:
        content.append({"type":"text","text":prefix})
    content.append({"type":"text","text":text,"marks":[{"type":"link","attrs":{"href":url}}]})
    if suffix:
        content.append({"type":"text","text":suffix})
    return {"type":"paragraph","content":content}

description_adf = {"type":"doc","version":1,"content":[
    h("Summary"),
    para("When a customer pays by PayPal on the new MSC website, the OPT booking reference is not available at the time of payment capture, leaving the Finance team unable to reconcile PayPal transactions to bookings without manual intervention. The agreed short-term solution (ADR0023 Option B) is to pass the acquirerAuthorizationCode — a unique reference shared between DataTrans and PayPal at the time of authorisation — through to SAP via the existing optional field DtsApplyPaymentRequestMessage.Payment.ReferenceNo in the Apply Payment API. This change affects two existing interfaces: INT007 (DTS Apply Payment – booking funnel) and INT146 (DTS Apply Payment – MyMSC private area)."),
    h("Change Scope"),
    bullets([
        "INT007 and INT146 must source acquirerAuthorizationCode from the DataTrans status response (detail.authorize.acquirerAuthorizationCode) when the transaction is in \"authorized\" state (e.g. Klarna), where the value is already present in the status response.",
        "INT007 and INT146 must source acquirerAuthorizationCode from the DataTrans authorize-split response (detail.authorize.acquirerAuthorizationCode) when the transaction is in \"authenticated\" state (e.g. PayPal, Card, Apple Pay, Google Pay), where the value is absent from the status response.",
        "When an acquirerAuthorizationCode is available, both interfaces must map it to DtsApplyPaymentRequestMessage.Payment.ReferenceNo before calling the DTS Apply Payment API.",
        "When no acquirerAuthorizationCode is available for a given payment method (e.g. Card, Apple Pay, Google Pay), ReferenceNo must be left absent or null and the Apply Payment call must proceed without error.",
        "The acquirerAuthorizationCode value must be passed through to SAP without any transformation, truncation, or encoding.",
        "No new API fields are introduced and no changes are required to the DTS Apply Payment API contract or to existing API consumers.",
    ]),
    h("Interfaces Affected"),
    bullets([
        "INT007 — DTS Apply Payment – booking funnel (MuleSoft, DataTrans, DTS, SAP): INT007 must be updated to extract detail.authorize.acquirerAuthorizationCode from the DataTrans status response (transaction in \"authorized\" state) or from the DataTrans authorize-split response (transaction in \"authenticated\" state), and populate DtsApplyPaymentRequestMessage.Payment.ReferenceNo with this value before calling the DTS Apply Payment API. If no acquirerAuthorizationCode is available, ReferenceNo is left absent or null and no error is raised.",
        "INT146 — DTS Apply Payment – MyMSC private area (MuleSoft, DataTrans, DTS, SAP): INT146 must apply the same sourcing and mapping logic as INT007: extract detail.authorize.acquirerAuthorizationCode from the appropriate DataTrans response based on transaction state and populate DtsApplyPaymentRequestMessage.Payment.ReferenceNo accordingly. If no acquirerAuthorizationCode is available, ReferenceNo is left absent or null and no error is raised.",
    ]),
    h("Rationale"),
    bullets([
        "On the old MSC website the OPT booking was created before payment, so the booking reference was available in PayPal at capture time; on the new website the booking is created after payment, meaning no booking reference is present at the point of PayPal capture.",
        "This leaves the Finance team unable to automatically reconcile PayPal transactions to bookings, creating a manual overhead and a risk of unmatched payments.",
        "The acquirerAuthorizationCode is generated by DataTrans during the authorisation step, is shared with PayPal, and provides SAP with a reliable reconciliation key that matches a value visible in both the DataTrans portal and PayPal.",
        "ADR0023 evaluated multiple options; the preferred long-term solution (DataTrans PATCH API to write the booking reference back to PayPal post-capture) is not achievable in the near term as it is not on the DataTrans roadmap.",
        "Reusing the existing optional field ReferenceNo in the Apply Payment request requires no DTS API development, has no impact on existing API consumers, and is the lowest-risk near-term option (ADR0023 Option B).",
    ]),
    h("Resources & Dependencies"),
    bullets([
        "ADR0023 – PayPal Order Identifier Reconciliation — Enterprise Architecture — https://msccruises.atlassian.net/wiki/spaces/EA/pages/4381835266/ADR0023+-+Paypal+Order+Identifier+Reconciliation",
        "MS PayPal Reconciliation – Confluence page — DTTP programme — https://msccruises.atlassian.net/wiki/spaces/DTP/pages/5379063893/MS+Paypal+Reconciliation",
    ]),
]}

ac_adf = {"type":"doc","version":1,"content":[
    h("AC1 — PayPal authenticated state: INT007 sources auth code from authorize-split"),
    para("Given a PayPal payment has been completed in the booking funnel and the DataTrans transaction is in \"authenticated\" state when INT007 calls the status endpoint"),
    para("When INT007 calls the DataTrans authorize-split endpoint and receives a response containing detail.authorize.acquirerAuthorizationCode"),
    para("Then INT007 maps the acquirerAuthorizationCode to DtsApplyPaymentRequestMessage.Payment.ReferenceNo and calls the DTS Apply Payment API with the field populated; the value matches the \"Acquirer authoriz code\" visible in the DataTrans portal for the same transaction"),
    h("AC2 — INT007 Apply Payment API call: correct contract"),
    para("Given INT007 has successfully retrieved the acquirerAuthorizationCode from the DataTrans authorisation response"),
    para("When INT007 calls the DTS Apply Payment API"),
    para("Then INT007 uses the correct HTTP method, endpoint URL, authentication headers, and payload schema; the request body conforms to the DtsApplyPaymentRequestMessage schema with Payment.ReferenceNo populated; the DTS Apply Payment API returns the agreed success response code"),
    h("AC3 — PayPal authenticated state: INT146 sources auth code from authorize-split"),
    para("Given a PayPal payment has been completed in the MyMSC private area and the DataTrans transaction is in \"authenticated\" state"),
    para("When INT146 calls the DataTrans authorize-split endpoint and receives a response containing detail.authorize.acquirerAuthorizationCode"),
    para("Then INT146 maps the value to DtsApplyPaymentRequestMessage.Payment.ReferenceNo and calls the DTS Apply Payment API; the value matches the DataTrans portal entry for the same transaction"),
    h("AC4 — INT146 Apply Payment API call: correct contract"),
    para("Given INT146 has successfully retrieved the acquirerAuthorizationCode from the DataTrans authorisation response"),
    para("When INT146 calls the DTS Apply Payment API"),
    para("Then INT146 uses the correct HTTP method, endpoint URL, authentication, and payload schema; the request body conforms to the DtsApplyPaymentRequestMessage schema with Payment.ReferenceNo populated; the DTS Apply Payment API returns the agreed success response code"),
    h("AC5 — Klarna authorized state: auth code sourced from status response"),
    para("Given a Klarna payment has been completed and the DataTrans transaction is in \"authorized\" state when INT007 or INT146 calls the status endpoint"),
    para("When the integration reads detail.authorize.acquirerAuthorizationCode from the DataTrans status response"),
    para("Then the integration maps the value to DtsApplyPaymentRequestMessage.Payment.ReferenceNo and calls the DTS Apply Payment API without making an additional authorize-split call; SAP receives the Apply Payment request with the correct ReferenceNo value"),
    h("AC6 — Klarna: no redundant authorize-split call"),
    para("Given a Klarna payment where the DataTrans status response already contains the acquirerAuthorizationCode"),
    para("When the integration processes the payment"),
    para("Then the integration does not make an additional authorize-split call to obtain the acquirerAuthorizationCode; the value in Payment.ReferenceNo matches the value from the status response"),
    h("AC7 — Card payment: ReferenceNo absent, no error"),
    para("Given a Card payment processed via INT007 or INT146 where neither the DataTrans status response nor the authorisation response contains an acquirerAuthorizationCode"),
    para("When the integration calls the DTS Apply Payment API"),
    para("Then the Apply Payment request is sent with Payment.ReferenceNo absent or null; the DTS Apply Payment API accepts the request and returns the agreed success code; no error is logged for the absence of ReferenceNo"),
    h("AC8 — Apple Pay / Google Pay: ReferenceNo absent, no error"),
    para("Given an Apple Pay or Google Pay payment processed via INT007 or INT146 where no acquirerAuthorizationCode is available"),
    para("When the integration calls the DTS Apply Payment API"),
    para("Then the Apply Payment request is sent without ReferenceNo; the DTS Apply Payment API returns the agreed success code; the integration completes successfully; no error is logged for the missing acquirerAuthorizationCode"),
]}

payload = {"fields": {"description": description_adf, "customfield_11506": ac_adf}}
data = json.dumps(payload).encode("utf-8")
req = urllib.request.Request(
    f"{JIRA_URL}/rest/api/3/issue/DTTP25-19655",
    data=data, method="PUT",
    headers={"Authorization": f"Basic {auth}", "Content-Type": "application/json", "Accept": "application/json"}
)
ssl_ctx = ssl.create_default_context(cafile=certifi.where())
try:
    with urllib.request.urlopen(req, context=ssl_ctx) as resp:
        print(f"SUCCESS: {resp.status}")
except urllib.error.HTTPError as e:
    print(f"ERROR {e.code}: {e.read().decode()}")
